---
- hosts: all
  roles:
    - role: {{ cookiecutter.ansible_bootstrap_role }}
      tags: bootstrap

- import_playbook: play_dev.yml

- import_playbook: play_{{ cookiecutter.vm_ansible_group }}.yml
